{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          },
          "reason": "activity is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.2"
          },
          "reason": "activity is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-1.8.2.aar",
          "url": "activity-1.8.2.aar",
          "size": 169675,
          "sha512": "908ef26ff1a4dd2f6b496e88fd60b5b736e903e1d33799234a9944916392ceefa3e391c147899bdbdc319a7598042d64ed3d12c778940d90de52c443a95ff31e",
          "sha256": "ecc119262530a6e2f9f373207e472d476306bed3d4b216fe61b1ea42e3bef688",
          "sha1": "bce54c84024b17c34f9d4cdeaf1ce39d3e750c9e",
          "md5": "d697c391165d9d716d4888fe692f936f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          },
          "reason": "activity is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.2"
          },
          "reason": "activity is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-1.8.2.aar",
          "url": "activity-1.8.2.aar",
          "size": 169675,
          "sha512": "908ef26ff1a4dd2f6b496e88fd60b5b736e903e1d33799234a9944916392ceefa3e391c147899bdbdc319a7598042d64ed3d12c778940d90de52c443a95ff31e",
          "sha256": "ecc119262530a6e2f9f373207e472d476306bed3d4b216fe61b1ea42e3bef688",
          "sha1": "bce54c84024b17c34f9d4cdeaf1ce39d3e750c9e",
          "md5": "d697c391165d9d716d4888fe692f936f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          },
          "reason": "activity is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.2"
          },
          "reason": "activity is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-1.8.2-sources.jar",
          "url": "activity-1.8.2-sources.jar",
          "size": 54490,
          "sha512": "340a6a9b0398d37aefa4d0edf7bde2a666456cd02d5066a9123b9b3afeae7b23ea887d27b8d92d8dfe7a7635f4fa6b92eb4faaadd5d2d8a1c5daa7dda3fff2ca",
          "sha256": "9b95814f98aba0a72c3f2396290e8476215f3cc0bd9ac656babfce45b500fe76",
          "sha1": "4db2a2efa9046d2bde019dddc6c857c8f67a50cf",
          "md5": "9fecaae5114beed32df09b188e339c62"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          },
          "reason": "activity is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.2"
          },
          "reason": "activity is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-1.8.2-versionMetadata.json",
          "url": "activity-1.8.2-versionMetadata.json",
          "size": 28752,
          "sha512": "92b2b547f662bd91ee9cb718cad841ebbe48d69acf8ddb30219ba6ec03bfb2beeb265156dffb1c2ac4ceed3b3971dece2524073bf37f4a9fd7209269f171df57",
          "sha256": "244337794c04662e01b6ace3f754698d7cea1bc44bbe7384a3722849a857724d",
          "sha1": "e76562b71af2fef2b06653bf22f3ab0c83298345",
          "md5": "dd9c7efa06e119e93fd646e691283b96"
        }
      ]
    }
  ]
}